### ISSUE TITLE
That question on free-software definition: Can you give me an example of not "gratis" free software?

### ISSUE THREAD

**Issue by melloc01** [fczuardi/free-software-bridge#1]
> Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, “free software” is a matter of liberty, not price. To understand the concept, you should think of “free” as in “free speech,” not as in “free beer”. We sometimes call it “libre software,” borrowing the French or Spanish word for “free” as in freedom, to show we do not mean the software is gratis.

#### Can you give me an example of not "gratis" free software?

I was thinking maybe my question was not very well put - also not well thought - but I was thinking and another possible answer for it could be:

#### The point is not **not being gratis and being free software**. The point in this definition is that there is **gratis software that is not free**.

Also, charging for "building a website" and publishing it as MIT, and various another points you raised on your answer makes a lot of sense and totally answer it, was just to add to your answer @fczuardi, what do you think?

**Comment by fczuardi** [comment]
Examples of software that are free software but that the people charge for the binaries:

## Ardour:

https://community.ardour.org/download

![screen shot 2017-02-12 at 10 43 06](https://cloud.githubusercontent.com/assets/7760/22862146/28547c04-f110-11e6-8fb1-72d4f7dbf29e.png)

**Comment by fczuardi** [comment]
Commercial games with the source code released (some of them under free-software licenses): https://en.wikipedia.org/wiki/List_of_commercial_video_games_with_available_source_code

**Comment by fczuardi** [comment]
Another extensive list, with good examples such as Blender, Doom, Textmate…:
https://en.wikipedia.org/wiki/List_of_commercial_software_with_available_source_code

**Comment by melloc01** [comment]
sweet :clap: ,
and those examples back up, even more, your answer =]
